### ISSUE TITLE
Destination path already exists

### ISSUE THREAD

**Issue by kranix0** [zach-snell/slack-export#1]
Nice script, thanks!

I can get it to export my public channels but it aborts on a private channel:

```
Getting history for Private Channels and Group Messages
getting history for private channel leadership with id GAEV6SYV6
getting history for private channel leadership-archived with id GAGH528MC
Traceback (most recent call last):
  File "slack_export.py", line 339, in <module>
    getPrivateChannels()
  File "slack_export.py", line 214, in getPrivateChannels
    parseMessages( groupDir, messages, 'group' )
  File "slack_export.py", line 127, in parseMessages
    channelRename( oldRoomPath, newRoomPath )
  File "slack_export.py", line 89, in channelRename
    shutil.move( os.path.join( oldRoomName, fileName ), newRoomName )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path 'leadership-archived/.json' already exists
```

**Comment by zach-snell** [comment]
Yeah I could see this likely happening if you have at one point renamed a channel to match the name of a previously existing channel that has since been renamed. 

That or you exported to the same place twice somehow which I don't think is possible.
Could work around this by fiddling with the way the channel export/move logic works.

Very minor though you could just export specific private channels to avoid hitting this.

**Comment by kranix0** [comment]
I initially thought it may be because this was a group DM that was converted into a private channel.

If that were the case, I would have expected there to be a clear break in terms of date. So the messages would be in the first channel ('leadership-archived') and then at some date they would continue on in 'leadership'. But that's not the case; they are mixed. The 'leadership' channel has most of the messages and a few random days are archived in 'leadership'. I can't see any pattern here.
